### ISSUE TITLE
Propose new RL and DeepRL algorithms

### ISSUE THREAD

**Issue by ghost** [JdeRobot/dl-learning#6]
Propose a set of new RL and DeepRL algorithms.

**Comment by RUFFY-369** [comment]
Is this repo under construction? And  also I would like to propose some sets of DeeRL algos ranging from SAC, DDPG to PPO-Penalty & PPO-Clip.

**Comment by jmplaza** [comment]
Hi @RUFFY-369 , yes, this repository is deprecated. Feel free to use [BehaviorStudio](https://github.com/JdeRobot/BehaviorStudio) (soon it will be renamed to BehaviorMetrics), and work on RL and DeepRL algorithms there, we have centered the algorithms there around the Car-Autonomous-Driving application. Soon we will also expand it to drone navigation.
